apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: namespace-approval-creds
  namespace: sonataflow-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: namespace-approval-creds
  data:
    - secretKey: BACKSTAGE_NOTIFICATIONS_URL
      remoteRef:
        key: orchestrator/namespace-approval
        property: BACKSTAGE_NOTIFICATIONS_URL
    - secretKey: NOTIFICATIONS_BEARER_TOKEN
      remoteRef:
        key: orchestrator/namespace-approval
        property: NOTIFICATIONS_BEARER_TOKEN
    - secretKey: AAP_URL
      remoteRef:
        key: orchestrator/namespace-approval
        property: AAP_URL
    - secretKey: aap_token
      remoteRef:
        key: orchestrator/namespace-approval
        property: aap_token
