# Backstage Notifications service
quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL}
quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}

# AAP Controller (OpenAPI)
quarkus.rest-client.aap.url=https://aap.ultra.lab
quarkus.openapi-generator.aap.auth.BearerToken.bearer-token=${aap_token}

# Workflow callback URL
kogito.service.url=http://namespace-approval.sonataflow-infra

# Messaging channels
mp.messaging.outgoing.kogito-job-service-job-request-events.connector=quarkus-http
mp.messaging.outgoing.kogito-job-service-job-request-events.url=http://sonataflow-platform-jobs-service.sonataflow-infra/v2/jobs/events
mp.messaging.outgoing.kogito-processdefinitions-events.connector=quarkus-http
mp.messaging.outgoing.kogito-processdefinitions-events.url=http://sonataflow-platform-data-index-service.sonataflow-infra/definitions
mp.messaging.outgoing.kogito-processinstances-events.connector=quarkus-http
mp.messaging.outgoing.kogito-processinstances-events.url=http://sonataflow-platform-data-index-service.sonataflow-infra/processes

# Trust self-signed certs
quarkus.tls.trust-all=true

# Logging
quarkus.log.level=INFO

# Persistence
kie.flyway.enabled=true
