# Backstage Notifications service
quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL}
quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}

# AAP Controller (via Nginx proxy on Wing)
kogito.sw.functions.launchAAPJobTemplate.host=${AAP_URL}
kogito.sw.functions.launchAAPJobTemplate.port=443
kogito.sw.functions.getAAPJobStatus.host=${AAP_URL}
kogito.sw.functions.getAAPJobStatus.port=443

# Trust self-signed certs
quarkus.tls.trust-all=true

# Logging
quarkus.log.level=INFO

# Persistence
kie.flyway.enabled=true
